#!/bin/bash

#
# Outputs the name of the first remote that contains the current commit
#

branch="$1"
if [ -z "$branch" ]; then
  branch="$(git me)"
fi

remote="$(git branch --remote --contains $branch | grep $branch | head -n 1)"
if [ "$remote" ]; then
  echo $remote | sed 's/[ ]*//' | sed 's/\/.*//'
fi

