#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"
fallback="darren" # branch to transition to

# prevent destruction of the master branch
if [ $branch == "master" ]; then
  echo "Cannot kill master"
  exit 1
fi

# remove branch from fork
if [ "$(git branch --remote | grep fork/$branch)" ]; then
  echo "Deleting $branch from fork..."
  git push fork :$branch
fi

# remove branch from origin
if [ "$(git branch --remote | grep origin/$branch)" ]; then
  echo "Deleting $branch from origin..."
  git push origin :$branch
fi

# check out fallback branch
if [ $branch != $fallback ]; then

  # if fallback branch already exists:
  #   * check it out
  #   * destroy local branch
  # otherwise:
  #   * create the fallback branch
  #   * reset the branch to origin/master
  #   * destroy local branch
  if [ "$(git branch | grep $fallback)" ]; then
    git checkout $fallback
    if [ "$1" == "--force" ]; then
      git branch -D $branch
    fi
  else
    git checkout -b $fallback
    git reset --hard origin/master
    if [ "$1" == "--force" ]; then
      git branch -D $branch
    fi
  fi
fi

