source 'http://rubygems.org'

gem 'rails'
gem 'jira-cli'
gem 'tmuxinator'
gem 'foreman'
gem 'powder'
gem 'cocoapods'
gem 'pry'
gem 'pry-remote'
gem 'rails', '3.2.18'
gem 'rails', '4.0.5'
gem 'rubocop'
gem 'awesome_print'
