" Default VIM configuration
syntax on
set tabstop=2
set shiftwidth=2
set expandtab
set number
set vb
set clipboard=unnamed
au BufEnter Makefile set noexpandtab sts=0
au BufEnter makefile set noexpandtab sts=0
filetype plugin indent on
autocmd BufWritePre * :%s/\s\+$//e
let mapleader = ","
set cursorline
set hlsearch
call pathogen#infect()

" Configure UI
set background=dark
colorscheme jellybeans
set transparency=3
set cc=80
hi ColorColumn ctermbg=Black guibg=Black

" Default mappings
nnoremap <silent> <leader><space> :e `pwd`<cr>
nnoremap <silent> <D-d> :Ex<cr>
nnoremap <silent> <leader>s :FSHere<cr>
noremap <silent> <D-k> :noh<cr>
noremap <silent>  /\.\.<cr>

" Grep configuration
nnoremap <D-F> :grep -irn<Space>
nmap <silent> <C-]> :cn<CR>z.
nmap <silent> <C-[> :cp<CR>z.

" reindent current file and return to previous location
map <D-i> mzgg=G`z<CR>

" Easy Motion
hi EasyMotionTarget ctermbg=DarkMagenta guibg=DarkMagenta ctermfg=white guifg=white

" configure sign column
highlight clear SignColumn
sign define dummy
execute 'sign place 9999 line=1 name=dummy buffer=' . bufnr('')

" YouCompleteMe
"   configure autocompletion keys
let g:ycm_key_list_select_completion = ['<D-]>']
let g:ycm_key_list_previous_completion = ['<D-[>']

" Vim Airline Support
set laststatus=2
set noshowmode
set guifont=Menlo\ for\ Powerline:h13
let g:Powerline_symbols = 'fancy'
let g:airline_symbols = {}
let g:airline_left_sep = '⮀'
let g:airline_left_alt_sep = '⮁'
let g:airline_right_sep = '⮂'
let g:airline_right_alt_sep = '⮃'
let g:airline_symbols.branch = '⭠'
let g:airline_symbols.readonly = '⭤'
let g:airline_symbols.linenr = '⭡'

" CtrlP Options
let g:ctrlp_show_hidden = 1
noremap <silent> <leader>t :CtrlP<cr>
noremap <silent> <D-1> :let g:ctrlp_working_path_mode = 'ra'<cr>
noremap <silent> <D-2> :let g:ctrlp_working_path_mode = 'ca'<cr>
noremap <silent> <D-r> :CtrlPClearCache<cr>
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]((\.(git|hg|svn))|(coverage))$',
  \ 'file': '\v\.(swp|zip|DS_Store|jira-url)$'
  \ }

" Rainbow Parentheses
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" vim-easy-align mapping
vnoremap <silent> <Enter> :EasyAlign<cr>

" vim-gitgutter options
let g:gitgutter_eager = 0

" vim-turbox
let g:no_turbux_mappings = 1
nmap <leader>r <Plug>SendTestToTmux
nmap <leader>R <Plug>SendFocusedTestToTmux
