# Include ~/bin scripts in PATH
export PATH=$HOME/bin:$PATH
# Include ~/.secure scripts in PATH
export PATH=$HOME/.secure:$PATH
# Include Homebrew in PATH
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
# Include git extensions in PATH
export PATH=$HOME/.git-extensions:$PATH
# Include MySQL in PATH
export PATH=/usr/local/mysql/bin:$PATH
# Include Android tools in PATH
export PATH=$HOME/Library/Android/sdk/platform-tools:$PATH
export PATH=$HOME/Library/Android/sdk/tools:$PATH
# Load rbenv
export PATH=/Users/$(whoami)/.rbenv/shims:$(brew --prefix rbenv)/bin:$PATH
eval "$(rbenv init - zsh)"
# Include binstubs in path
export PATH=.bundle/bin:$PATH
# Set $DOTS
export DOTS="$HOME/Development/dotfiles"
# Set $VIMRUNTIME to support neovim
export VIMRUNTIME="$(brew --prefix macvim | sed 's/macvim//')$(readlink `brew --prefix macvim`)/MacVim.app/Contents/Resources/vim/runtime"
# Set default Postgres host and port
export PGHOST=localhost
export PGPORT=5432
