# antibody bundles
source ~/.bundles

# config
source $HOME/.dots/zsh/basic.zsh
source $HOME/.dots/zsh/colors.zsh
source $HOME/.dots/zsh/history.zsh
source $HOME/.dots/zsh/prompt.zsh
source $HOME/.dots/zsh/completion.zsh
source $HOME/.dots/zsh/aliases.zsh
source $HOME/.dots/zsh/functions.zsh
source $HOME/.dots/zsh/bindings.zsh
source $HOME/.dots/zsh/settings.zsh

# autoload tmux
if [ "$TMUX" = "" ]; then smux master; fi
