# load zinit
source $(brew --prefix)/opt/zinit/zinit.zsh
source $DOTS/zsh/plugins.zsh

# config
source $DOTS/zsh/basic.zsh
source $DOTS/zsh/colors.zsh
source $DOTS/zsh/history.zsh
source $DOTS/zsh/prompt.zsh
source $DOTS/zsh/completion.zsh
for file in $DOTS/zsh/completion/*.zsh; do
  source "$file"
done
source $DOTS/zsh/aliases.zsh
source $DOTS/zsh/functions.zsh

# bundle settings and bindings
source $DOTS/zsh/settings.zsh
source $DOTS/zsh/bindings.zsh

# load custom configuration
source $HOME/.dots/sys/env 2>/dev/null
source $HOME/.thanx/env 2>/dev/null

# autoload tmux
if [ "$TMUX" = "" ]; then tmux-start master && exit; fi

if [ -n "$TMUX" ]; then
  # Load zoxide
  eval "$(zoxide init zsh)"

  # Load atuin
  ATUIN_NOBIND=true eval "$(atuin init zsh)"
fi

export VIRTUALENVWRAPPER_PYTHON=`which python3`
# source `which virtualenvwrapper.sh`

source $HOME/.asdf/installs/python/3.9.1/bin/virtualenvwrapper.sh
