#!/bin/bash

#
# If the branch matches the JIRA issue regex (TA-****) and the summary doesn't
# already have a JIRA issue regex prefix, then prepend the branch name to the
# commit summary.
#

summary="$(cat "$1")"
branch="$(git rev-parse --abbrev-ref HEAD)"
regex="^[A-Z][A-Z][A-Z]?-.*"
if [[ "$branch" =~ $regex ]] && ! [[ "$summary" =~ $regex ]]; then
  echo -e "\033[1;34mPrepending \033[1;35m$branch\033[1;34m.\033[0m"
  echo "$branch. $summary" > "$1"
fi
