#!/bin/bash

#
# Prints the path (author/repo) of the input remote. Remote defaults to upstream
# if no remote is input.
#

full=`git address $1`
if [[ "$full" =~ "https" ]]; then
  echo $full | sed 's#.*\.com\/##g' | sed 's#.git$##g'
else
  echo $full | sed 's#.*:##g' | sed 's#.git$##g'
fi
