#!/bin/bash

#
# Dynamically determines and creates a pull request for the current commit
# against the nearest ancestor branch that is not the currently pushed branch.
#

# abort if not in git directory
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "Aborting. Not in a git repository."
  exit 1
fi

# specify the root url
source="https://github.com"

# path of ancestor's remote
path="$(git path)"

# get current branch
current_branch="$(git me)"
# determine the remote that contains the current branch
current_remote="$(git remote-contains $current_branch)"
# determine the author of the current remote
current_author="$(git author $current_remote)"
# set current (remote/branch) variable
current="$current_remote/$current_branch"

# determine ancestor (remote:branch), excluding the current (remote/branch)
ancestor="$(git ancestor $current | sed 's/\//:/')"
# determine remote of ancestor
ancestor_remote="$(echo $ancestor | sed 's/:.*//')"
# determine branch of ancestor
ancestor_branch="$(echo $ancestor | sed 's/.*://')"
# determine the author of the ancestor remote
ancestor_author="$(git author $ancestor_remote)"

# open the web browser at the computed pull request endpoint
open $source/$path/compare/$ancestor_author:$ancestor_branch...$current_author:$current_branch
