#!/bin/bash

#
# Displays the current branch in github if it exists upstream or on origin
#

branch="$(git me)"
remote=""

# if the current branch exists on origin, show that branch
if [ "$(git branch --remote | grep upstream/$branch)" ]; then
  remote="upstream"
fi

# if current branch is not on origin
if [ -z "$remote" ]; then
  # if the current branch exists on origin, show that branch
  if [ "$(git branch --remote | grep "origin/$branch")" ]; then
    remote="origin"
  fi
fi

if [ -z "$remote" ]; then
  # default to browsing master on either upstream or origin
  hub browse $(git path) tree/master
else
  # determine full remote path
  remote="$(git remote -v | grep $remote | awk '{print $2}' | uniq | sed 's#.*:##g' | sed 's#.git$##g')"
  hub browse $remote tree/$branch
fi
