#!/bin/bash

#
# Outputs the first commit message on the current or specified branch in the
# following format:
#   (yyyy-mm-dd) [author] commit message
#

pretty='(%Cblue%cd%Creset) [%C(bold cyan)%an%Creset] %C(bold white)%s%Creset'
echo "$(git log ${1:HEAD} -n 1 --pretty="$pretty" --abbrev-commit --date=short)"
