#!/bin/bash

#
# Outputs the name of the first remote that contains the current commit
#

branch="$1"
if [ -z "$branch" ]; then
  branch="$(git me)"
fi

# determine remote branch that contains the specified branch
remote="$(
  git branch --remote --contains $branch |
  grep $branch |
  head -n 1
)"

# echo the remote or nothing
if [ "$remote" ]; then
  echo $remote | sed 's/[ ]*//' | sed 's/\/.*//'
fi

