#!/bin/bash

#
# Pushes the current branch to:
#   * specified or current branch
#   * fork if it exists, origin otherwise
# Optional set --force to force push commit
#

branch="$(git me)"

# determine destination branch
dest="$(git me)"
if [ "$1" ] && [ "$1" != "--force" ]; then
  dest="$1"
fi

# abort script if input remote doesn't exist
if [ "$remote" ] && [ -z "$(git remote | grep $remote)"]; then
  echo "Aborting... no remote $remote exists."
  exit 0
fi

# set remote to fork or origin
remote="$(git remote | grep 'fork')"
if [ -z "$remote" ]; then
  remote="origin"
fi

# output description of actions
prefix="Pushing"
if [ "$1" == "--force" ] || [ "$2" == "--force" ]; then
  prefix="Force pushing"
fi
if [ $branch == $dest ]; then
  echo "$prefix $branch to $remote..."
else
  echo "$prefix $branch to $remote/$dest..."
fi

# push or force push depending on remote and flags
if [ $remote == "origin" ] && [ "$1" != "--force" ] && [ "$2" != "--force" ]; then
  git push $remote $branch
else
  git push $remote $branch -f
fi
