#!/usr/bin/ruby

#
# Generates a new git tag based off of the latest tag
#

tag = `git describe --abbrev=0 --tags 2>/dev/null`.strip
if !tag.match(/^(v)?\d+\.\d+\.\d+$/)
  puts "Sorry, no pre-existing semver tags."
  exit 1
end

versions = tag.scan(/\d+/)

prefix = 'v' if tag[0] == 'v'
major = versions[0].to_i
minor = versions[1].to_i
patch = versions[2].to_i

updated = ->{ "#{prefix}#{major}.#{minor}.#{patch}" }

case ARGV[0]
when "major"
  major += 1
when "minor"
  minor += 1
when "patch"
  patch += 1
end

if updated.call != tag
  print "Update #{tag} to #{updated.call}? (y/n) "
  confirm = $stdin.gets
  if confirm[0] == 'y'
    `git tag -a #{updated.call} -m ''`
    puts "Updated to #{updated.call}"
  end
else
  puts "Current version is #{tag}"
end

