#!/bin/bash

#
# Prints the address (git@github.com:author/repo.git) of the input remote.
# Remote defaults to upstream if no remote is input.
#

# determine which remote to determine address for
remote="$1"
if [ -z "$remote" ]; then
  remote="upstream"
fi

# determine remote address
git remote -v | grep $remote | awk '{print $2}' | uniq
