#!/usr/bin/ruby

#
# Thanx engineering git remote management.
#

REMOTES = {
  aaron: {
    username: :anutron,
    exceptions: { 'thanx-core' => 'thanx-web' }
  },
  davy: {
    username: :davywentworth,
    exceptions: { 'thanx-core' => 'thanx-web' }
  },
  marc: {
    username: :marcferna,
    exceptions: { 'thanx-core' => 'thanx-web' }
  },
  fletch: { username: :fzf },
  roy:    { username: :theElectricMiracleCat }
}.freeze

REPO = `git repo`.strip.freeze

def usage; puts 'Usage: git thanx [add/remove]' end

(usage; exit) if ARGV.count != 1
case ARGV[0]
when 'add'
  REMOTES.each do |remote, info|
    repo = (info[:exceptions] || {})[REPO] || REPO
    address = "git@github.com:#{info[:username]}/#{repo}"
    `git remote add #{remote} #{address} 2>/dev/null`
  end
  puts 'Successfully added Thanx remotes'
when 'remove'
  REMOTES.each do |remote, _|
    `git remote remove #{remote} 2>/dev/null`
  end
  puts 'Successfully removed Thanx remotes'
end
