#!/bin/bash

#
# Outputs the diff --stat between the most recent two tags.
#

recent=$(git recent-tag)
last=$(git last-tag)
if [ -n "$recent" ] && [ -n "$last" ]; then
  echo "Comparing $last to $recent ..."
  sleep 1
fi
git diff --stat $last..$recent 2>/dev/null
exit 0
