#!/bin/bash

branch="$(git me)"
if [ "$(git remote | grep upstream)" ]; then
  remote="upstream"
else
  remote="origin"
fi

echo "Attempting to push local $branch to $remote/master..."
git push $remote $branch:master
