#!/bin/bash

#
# Fetches from input remote, upstream if it exists, origin otherwise.
#

if [ -n "$1" ]; then
  echo "Fetching $1 changes..."
  git fetch "$1"
  exit
fi

if git remote | grep -q upstream; then
  echo 'Fetching upstream changes...'
  git fetch upstream
  exit
fi

echo 'Fetching origin changes...'
git fetch
