#!/bin/bash

# Open browser to current repo's CI page. Either CircleCI or Github Actions

gitpath=$(git path 2>/dev/null)
if [ -z "$gitpath" ]; then exit 1; fi

gitroot=$(git root)

if [ -d "$gitroot/.github/workflows" ]; then
  open "https://github.com/$gitpath/actions"
fi

if [ -f "$gitroot/.circleci/config.yml" ]; then
  open "https://app.circleci.com/pipelines/github/$gitpath"
fi
