#!/bin/bash

#
# Ensure upstream remote exists. If it does not, create it with the same remote
# address as origin.
#

if [ -z "$(git remote | grep upstream)" ]; then
  git remote add upstream "$(git address)"
fi
