#!/bin/bash

# This shell script displays all blob objects in the repository, sorted from
# smallest to largest.
# https://stackoverflow.com/a/42544963/958331

git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| awk '/^blob/ {print substr($0,6)}' \
| sort --numeric-sort --key=2 \
| gcut --complement --characters=13-40 \
| gnumfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
