#!/bin/bash

# Opens your browser to the github pull request creation page for the current
# commit against the source branch.

# abort if not in git directory
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "Aborting. Not in a git repository."
  exit 1
fi

# specify the root url
root="https://github.com"

# author/repo of the default remote
path="$(git path)"

# get current branch
current_branch="$(git me)"
# determine the remote that contains the current branch
current_remote="$(git remote-contains $current_branch)"
# determine the author of the current remote
current_author="$(git author $current_remote)"
current="$current_author:$current_branch"

# determine source author and branch
source_branch="master"
if [ ! -z "$(git branch --remote | grep upstream/dev)" ]; then
  source_branch="dev"
fi
source_author="$(git author)"
source="$source_author:$source_branch"

# open the web browser at the computed pull request endpoint
open "$root/$path/compare/$source...$current"
