#!/bin/bash

#
# Rebase on top of upstream/dev if it exists. Otherwise, attempts to rebase
# on top of origin/dev.
#

if [ -n "$(git remote | grep "upstream")" ]; then
  git rebase upstream/dev $1
else
  git rebase origin/dev $1
fi
