#!/usr/bin/env ruby
# frozen_string_literal: true

#
# If the branch matches the JIRA issue regex (TA-****) and the summary doesn't
# already have a JIRA issue regex prefix, then prepend the branch name to the
# commit summary.
#

summary = File.read(ARGV[0])
branch = `git rev-parse --abbrev-ref HEAD`.strip
regex = /^[A-Z][A-Z]-/
exit unless branch.match?(regex)
exit if summary&.match?(regex)
File.write(ARGV[0], "#{branch}. #{summary}")
