#!/bin/bash

#
# Pushes the current branch upstream
#

if [ -z "$(git remote | grep upstream)" ]; then
  echo "No upstream remote to push to..."
  exit 1
fi

branch="$(git symbolic-ref --short HEAD)"

echo "Pushing local \`$branch\` to upstream/$branch..."
git push upstream $branch $1
