# config
source $DOTS/lib/zsh/basic.zsh
source $DOTS/lib/zsh/colors.zsh
source $DOTS/lib/zsh/history.zsh
source $DOTS/lib/zsh/prompt.zsh
source $DOTS/lib/zsh/completion.zsh
source $DOTS/lib/zsh/aliases.zsh
source $DOTS/lib/zsh/functions.zsh

# antibody bundles
source ~/.bundles

# bundle settings and bindings
source $DOTS/lib/zsh/settings.zsh
source $DOTS/lib/zsh/bindings.zsh

# autoload tmux
if [ "$TMUX" = "" ]; then tmux-start master; fi

# load pyenv shims
if [ -n "$TMUX" ]; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
