# System Aliases
alias ls='ls -G'
alias l='ls -lah'
alias la='ls -ah'
alias lr='ls -lR'
alias history='fc -l 1'
alias o='open'
alias o.='open .'

# Jump Aliases
alias dot='tmux rename-window dots 2>/dev/null; cd $DOTS'
alias dsk='tmux rename-window desktop 2>/dev/null; cd ~/Desktop'
alias dev='tmux rename-window dev 2>/dev/null; cd ~/Development'
alias doc='cd ~/Documents'
alias docs='cd ~/Documents'
alias down='tmux rename-window downloads 2>/dev/null; cd ~/Downloads'
alias evergreen='cd ~/.evergreen'
alias ev='evergreen'

# Command Aliases
alias orig='find . -iname "*.orig" | xargs rm'
alias gitx='open -a /Applications/GitX.app .'
alias update='dots update'
alias up='update'
alias shrink='. shrink'
alias unshrink='. unshrink'
alias h='history'
alias top='vtop'
alias binstubs='bundle install --binstubs .bundle/bin'
alias secure='v ~/.secure'
alias pad='notes scratch-pad'
alias v.='nvim .'
alias v='nvim'
alias vimdiff='mvim -d'
alias vi='vim'
alias g='git'
alias tf='terraform'
alias vimsync="dots install vim"
alias ff='fuzzy-find'
alias fff='fuzzy-find-file'
alias nuc='thanx nucleus'
alias nup='thanx nucleus update'
alias ver='thanx version'
alias vup='thanx version update'
alias t='thanx'
alias plane='airplane'
alias starwars='caffeinate -d telnet towel.blinkenlights.nl'
alias hc='heroku console'
alias notify='terminal-notifier -message'
alias jo='jira-open'
alias ycm='cd ~/.vim/plugged/YouCompleteMe; ./install.py'

# tmux-start shortcuts
alias mxm='unshrink; tmux-start master'
alias mxv='unshrink; tmux-start vertical'
